# Netlify Configuration for Next.js 14

# Build settings
[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Next.js specific settings
[[plugins]]
  package = "@netlify/plugin-nextjs"

# (Removed manual SPA redirect so Next.js plugin can manage routes)

# Environment variables (add your own in Netlify dashboard)
# NEXT_PUBLIC_ADSENSE_ID=your-adsense-id

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
